import fs from 'node:fs/promises';
import http from 'node:http';
import path from 'node:path';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
const require=createRequire('C:/Users/claud/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/package.json');
const {chromium}=require('playwright');
const root=path.resolve(new URL('..',import.meta.url).pathname.replace(/^\/(\w:)/,'$1'));
const server=http.createServer(async(req,res)=>{try{const target=path.resolve(root,'.'+decodeURIComponent(new URL(req.url,'http://localhost').pathname));if(!target.startsWith(root+path.sep))throw Error('path');const body=await fs.readFile(target);res.setHeader('Content-Type',target.endsWith('.js')?'text/javascript':target.endsWith('.css')?'text/css':'text/html');res.end(body)}catch{res.statusCode=404;res.end('Not found')}});
await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const origin=`http://127.0.0.1:${server.address().port}`;
const browser=await chromium.launch({channel:'chrome',headless:true});
const context=await browser.newContext();const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
await context.route('**/*',route=>route.request().url().startsWith(origin+'/')?route.continue():route.abort());
try{
await page.goto(origin+'/tests/work-control-harness.html');await page.waitForFunction(()=>document.documentElement.dataset.ready==='1');
assert.deepEqual(errors,[]);
const costs=await page.evaluate(()=>ObraAtivaWorkControl.model('OBRA-TESTE').finance);
assert.equal(costs.labor,11.5);assert.equal(costs.received.total,113);assert.equal(costs.costs.total,42.5);
assert.equal(costs.phaseCosts[1].personDays,.5);assert.equal(costs.phaseCosts[1].people,1);
const original=await page.evaluate(()=>JSON.stringify({employees:db.employees,attendance:db.attendance,payments:db.payments,photos:db.workMedia,receipts:db.receipts,otherExpenses:db.otherExpenses,baseline:db.works[0].control}));
assert.equal(await page.locator('.simple-phase-folder').count(),6);
assert.equal(await page.locator('nav,.wc-health,.wc-radar').count(),0);
assert.match(await page.locator('[data-wc-phase="FASE-TESTE-1"] .wc-phase-labor').textContent(),/11,50/);
assert.match(await page.locator('[data-wc-phase="FASE-TESTE-0"] .wc-phase-labor').textContent(),/0,00/);
assert.equal(await page.evaluate(()=>persisted),0,'Renderização não altera registros');
await page.evaluate(()=>openInternalWorkModal('LEGADO-TESTE'));
await page.locator('[name=name]').fill('OBRA FICTÍCIA — Renomeada');await page.locator('#wc-form [type=submit]').click();
assert.equal(await page.evaluate(()=>db.works.find(w=>w.id==='LEGADO-TESTE').control),undefined);
assert.equal(await page.evaluate(()=>db.works.find(w=>w.id==='LEGADO-TESTE').legacyData),'PRESERVAR');
await page.evaluate(()=>openWorkTracker('OBRA-TESTE'));
await page.locator('[data-wc-action=progress][data-phase="FASE-TESTE-1"]').click();
assert.deepEqual(await page.locator('#wc-form [name]').evaluateAll(all=>all.map(e=>e.name)),['percent']);
await page.locator('[name=percent]').fill('55');await page.locator('#wc-form [type=submit]').click();
assert.equal(await page.evaluate(()=>db.workUpdates.at(-1).delta),15);
// A correção para baixo continua possível pelo editor da fase e mantém trilha.
await page.locator('[data-wc-action=progress][data-phase="FASE-TESTE-1"]').focus();
await page.keyboard.press('Enter');assert.equal(await page.evaluate(()=>legacyPhotos),0);
await page.locator('[name=percent]').fill('20');await page.locator('#wc-form [type=submit]').click();
assert.equal(await page.evaluate(()=>db.workPhases[1].percent),20);
assert.equal(await page.evaluate(()=>db.workUpdates.at(-1).before.percent),55);
await page.locator('.work-phase-folder-empty').first().click();assert.equal(await page.evaluate(()=>legacyPhotos),1);
await page.evaluate(()=>openWorkTracker('OBRA-TESTE'));
await page.locator('[data-work-phase-action=add-photo]').first().click();assert.equal(await page.evaluate(()=>legacyPhotoUploads),1);
await page.locator('[data-work-phase-action=new-phase]').click();await page.locator('[name=name]').fill('ETAPA FICTÍCIA NOVA');
await page.locator('#wc-form [type=submit]').click();assert.equal(await page.evaluate(()=>db.workPhases.length),7);
// Somente sugestões marcadas são criadas, com o percentual digitado.
await page.locator('[data-wc-action=template]').click();await page.locator('#wc-form [type=submit]').click();
assert.match(await page.locator('#wc-message').textContent(),/Marque pelo menos/);
await page.locator('[data-wc-suggestion="Fundação"]').check();
await page.locator('[data-wc-suggestion-percent="Fundação"]').fill('37');
await page.locator('[data-wc-suggestion="Pintura"]').check();
await page.locator('#wc-form [type=submit]').click();
assert.equal(await page.evaluate(()=>db.workPhases.length),9);
const suggestedId=await page.evaluate(()=>db.workPhases.find(p=>p.name==='Fundação').id);
assert.equal(await page.evaluate(id=>WorkTrackingService.phase(id).percent,suggestedId),37);
await page.locator('[data-wc-action=template]').click();
assert.ok(await page.locator('[data-wc-suggestion="Fundação"]').isDisabled());
await page.locator('[data-wc-action=close]').click();
await page.evaluate(()=>go('planning'));
await page.locator('[data-wc-plan-person="PESSOA-TESTE-A"]').selectOption(suggestedId);
await page.locator('[data-plan-employee="PESSOA-TESTE-B"]').check();
await page.locator('[data-wc-plan-person="PESSOA-TESTE-B"]').selectOption('FASE-TESTE-2');
await page.getByText('Salvar distribuição',{exact:true}).click();
assert.equal(await page.evaluate(()=>db.distributions.find(d=>d.employeeId==='PESSOA-TESTE-B').phaseId),'FASE-TESTE-2');
assert.equal(await page.locator('[data-wc-plan-person="PESSOA-TESTE-A"]').inputValue(),suggestedId);
await page.evaluate(()=>openWorkTracker('OBRA-TESTE'));
assert.match(await page.locator('[data-wc-phase="'+suggestedId+'"] .wc-phase-labor').textContent(),/11,50/);
assert.match(await page.locator('[data-wc-phase="FASE-TESTE-1"] .wc-phase-labor').textContent(),/0,00/);
assert.match(await page.locator('[data-wc-phase="FASE-TESTE-2"] .wc-phase-labor').textContent(),/0,00/,'Falta não custa diária');
assert.equal(await page.evaluate(()=>JSON.stringify({employees:db.employees,attendance:db.attendance,payments:db.payments,photos:db.workMedia,receipts:db.receipts,otherExpenses:db.otherExpenses,baseline:db.works[0].control})),original);
// Planejar o dia seguinte não gera custo nem presença.
await page.evaluate(()=>{planningDate='2031-01-16';go('planning')});
await page.locator('[data-plan-employee="PESSOA-TESTE-A"]').check();
await page.locator('[data-wc-plan-person="PESSOA-TESTE-A"]').selectOption(suggestedId);
await page.getByText('Salvar distribuição',{exact:true}).click();
assert.equal(await page.evaluate(()=>ObraAtivaWorkControl.model('OBRA-TESTE').finance.labor),11.5);
await page.evaluate(()=>{CompanyWorkspace.current.role='viewer';AccessControl.isReadOnly=()=>true;openWorkTracker('OBRA-TESTE')});
assert.equal(await page.locator('[data-wc-action=progress],[data-wc-action=template]').count(),0);
await page.evaluate(()=>{CompanyWorkspace.current.role='supervisor';AccessControl.isReadOnly=()=>false;AccessControl.allowedModules=()=>['works','planning'];render()});
assert.equal(await page.locator('.wc-phase-labor').count(),0);
assert.equal(await page.evaluate(()=>ObraAtivaWorkControl.model('OBRA-TESTE').finance),null);
await page.evaluate(()=>{CompanyWorkspace.current.role='owner';go('works')});
assert.equal(await page.locator('.legacy-card').count(),2);
assert.doesNotMatch(await page.locator('#view').textContent(),/Radar|Histórico e comparação/);
assert.deepEqual(errors,[]);
console.log('WORK_CONTROL_UI_OK: fases simples, sugestões selecionadas, percentual, escala, custo confirmado sem duplicidade, permissões e dados anteriores preservados; somente FICTÍCIOS.');
}finally{await browser.close();await new Promise(resolve=>server.close(resolve))}
