import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import test from 'node:test';
const source=fs.readFileSync(new URL('../public-assets/work-control-sync-v1.js',import.meta.url),'utf8');
function fixture(handler){const calls=[],events=[],state={CloudSync:{request:async(...args)=>{calls.push(args);return handler(...args)},schedule(){state.scheduled++}},CompanyWorkspace:{current:{id:'EMPRESA-TESTE'}},scheduled:0,URL,CustomEvent:class{constructor(type){this.type=type}},document:{dispatchEvent(e){events.push(e.type)}}};state.window=state;vm.runInNewContext(source,state);return{state,calls,events};}
const read='/rest/v1/company_app_state?company_id=eq.EMPRESA-TESTE&select=data,updated_at';
const write={method:'POST',body:JSON.stringify({p_company_id:'EMPRESA-TESTE',p_data:{db:{works:[{control:{version:1}}]}}})};
test('lê revisão, usa comparação no servidor e atualiza somente após confirmação',async()=>{const f=fixture(path=>path.includes('checked')?{revision:8,updated_at:'2031-01-15'}:[{work_control_revision:7}]);await f.state.CloudSync.request(read);assert.equal(f.state.ObraAtivaWorkSync.ready('EMPRESA-TESTE'),true);assert.match(f.calls[0][0],/work_control_revision/);const result=await f.state.CloudSync.request('/rest/v1/rpc/save_company_app_state',write);assert.equal(result,'2031-01-15');assert.equal(JSON.parse(f.calls[1][1].body).p_expected_revision,7);});
test('conflito não é reenviado automaticamente nem descartado silenciosamente',async()=>{const f=fixture(path=>{if(path.includes('checked'))throw Object.assign(new Error('Outra sessão salvou'),{code:'40001'});return[{work_control_revision:2}]});await f.state.CloudSync.request(read);await assert.rejects(()=>f.state.CloudSync.request('/rest/v1/rpc/save_company_app_state',write),/Outra sessão/);assert.equal(f.state.ObraAtivaWorkSync.ready('EMPRESA-TESTE'),false);assert.equal(f.events.length,1);f.state.CloudSync.schedule();assert.equal(f.state.scheduled,0);await assert.rejects(()=>f.state.CloudSync.request('/rest/v1/rpc/save_company_app_state',write),/cópia permanece/);assert.equal(f.calls.length,2);});
test('sem migration a versão antiga continua legível e não grava dados novos sem proteção',async()=>{const f=fixture(path=>{if(path.includes('work_control_revision'))throw Object.assign(new Error('work_control_revision'),{code:'42703'});return[{data:{}}]});await f.state.CloudSync.request(read);assert.equal(f.state.ObraAtivaWorkSync.ready('EMPRESA-TESTE'),false);assert.equal(f.calls.length,2);await assert.rejects(()=>f.state.CloudSync.request('/rest/v1/rpc/save_company_app_state',write),/precisa ser ativada/);});
test('erro de conexão preserva revisão e permite nova tentativa; não mistura empresas',async()=>{let fail=true;const f=fixture(path=>{if(path.includes('checked')){if(fail)throw Error('Sem conexão');return{revision:4,updated_at:'2031-01-15'}}return[{work_control_revision:3}]});await f.state.CloudSync.request(read);await assert.rejects(()=>f.state.CloudSync.request('/rest/v1/rpc/save_company_app_state',write),/Sem conexão/);assert.equal(f.state.ObraAtivaWorkSync.ready('OUTRA-EMPRESA-TESTE'),false);fail=false;await f.state.CloudSync.request('/rest/v1/rpc/save_company_app_state',write);assert.equal(JSON.parse(f.calls.at(-1)[1].body).p_expected_revision,3);});
