import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
const require = createRequire(import.meta.url), C = require('../public-assets/work-cost-core-v1.js'), W = require('../public-assets/work-control-core-v1.js');
let sequence = 0;
const ctx = { companyId: 'EMPRESA-TESTE', userId: 'USUARIO-TESTE', userName: 'GESTOR FICTÍCIO', now: '2031-01-15T12:00:00Z', today: '2031-01-15', id: () => `ID-TESTE-${++sequence}`, modules: ['works', 'planning', 'attendance', 'financial'], readOnly: false };
const initial = { companyId: ctx.companyId, works: [{ id: 'OBRA-TESTE-A', name: 'OBRA FICTÍCIA A', control: { baseline: { contractValue: 9181 } } }, { id: 'OBRA-TESTE-B', name: 'OBRA FICTÍCIA B' }], employees: [{ id: 'PESSOA-TESTE', name: 'PESSOA FICTÍCIA', status: 'Ativo', daily: 29 }], workPhases: [{ id: 'FASE-TESTE-A', workId: 'OBRA-TESTE-A', name: 'ETAPA FICTÍCIA' }, { id: 'FASE-TESTE-B', workId: 'OBRA-TESTE-B', name: 'OUTRA ETAPA FICTÍCIA' }], workUpdates: [], receipts: [], distributions: [], attendance: [], payments: [{ id: 'PAGAMENTO-DIARIA-TESTE', value: 29 }], otherExpenses: [], workMedia: [{ id: 'FOTO-ANTIGA-TESTE' }], receivables: [{ id: 'VALOR-TESTE', workId: 'OBRA-TESTE-A', total: 12347 }] };
const input = { employeeId: 'PESSOA-TESTE', name: 'SERVIÇO FICTÍCIO', mode: 'meters', quantity: 37.5, unitPrice: 19.3, start: '2031-01-01', end: '2031-02-01', phaseId: 'FASE-TESTE-A', operationId: 'OP-TESTE-1' };
const saved = C.saveContract(initial, 'OBRA-TESTE-A', input, ctx); let state = saved.state;
assert.equal(C.contracts(state, 'OBRA-TESTE-A')[0].total, 723.75);
assert.equal(C.contracts(initial, 'OBRA-TESTE-A').length, 0, 'operação pura preserva estado anterior');
assert.equal(C.contracts(C.saveContract(state, 'OBRA-TESTE-A', input, ctx).state, 'OBRA-TESTE-A').length, 1, 'reenvio não duplica');
const fixed = C.saveContract(state, 'OBRA-TESTE-B', { ...input, mode: 'fixed', total: 431, phaseId: 'FASE-TESTE-B', operationId: 'OP-TESTE-2' }, ctx); state = fixed.state;
assert.equal(C.contracts(state, 'OBRA-TESTE-B')[0].total, 431);
for (const [i, value] of [101.15, 79.6, 211.05].entries()) state = C.savePayment(state, 'OBRA-TESTE-A', saved.contractId, { value, date: ctx.today, phaseId: 'FASE-TESTE-A', note: 'QUINZENA FICTÍCIA', operationId: `PAGAMENTO-TESTE-${i}` }, ctx);
assert.deepEqual(C.totals(state, 'OBRA-TESTE-A', saved.contractId), { contracted: 723.75, paid: 391.8, outstanding: 331.95 });
const repeat = C.savePayment(state, 'OBRA-TESTE-A', saved.contractId, { value: 101.15, date: ctx.today, operationId: 'PAGAMENTO-TESTE-0' }, ctx);
assert.equal(C.payments(repeat, 'OBRA-TESTE-A').length, 3);
assert.throws(() => C.savePayment(state, 'OBRA-TESTE-A', saved.contractId, { value: 332, date: ctx.today, operationId: 'EXCESSO-TESTE' }, ctx), /saldo/);
assert.throws(() => C.savePayment(state, 'OBRA-TESTE-B', saved.contractId, { value: 1, date: ctx.today, operationId: 'CRUZADO-TESTE' }, ctx), /encontrada/);
state = C.saveExtra(state, 'OBRA-TESTE-A', { category: 'Combustível', value: 23.7, date: ctx.today, phaseId: 'FASE-TESTE-A', operationId: 'EXTRA-TESTE-1' }, ctx);
state = C.saveExtra(state, 'OBRA-TESTE-A', { category: 'Outro', customCategory: 'CUSTO FICTÍCIO PERSONALIZADO', value: 11.31, date: ctx.today, phaseId: '', operationId: 'EXTRA-TESTE-2' }, ctx);
assert.equal(C.totals(state, 'OBRA-TESTE-B').paid, 0);
assert.equal(state.otherExpenses.at(-1).phaseId, '');
assert.throws(() => C.saveExtra(state, 'OBRA-TESTE-A', { category: 'Outro', value: 1, date: ctx.today, operationId: 'INVALIDO-TESTE' }, ctx), /tipo/);
assert.throws(() => C.saveExtra(state, 'OBRA-TESTE-A', { category: 'Material', value: 1, date: ctx.today, phaseId: 'FASE-TESTE-B', operationId: 'INVALIDO-TESTE' }, ctx), /pertencer/);
for (const invalid of [0, -1, NaN, Infinity, 'abc', 1.001]) assert.throws(() => C.saveExtra(state, 'OBRA-TESTE-A', { category: 'Material', value: invalid, date: ctx.today, operationId: 'INVALIDO-TESTE' }, ctx));
assert.throws(() => C.saveExtra(state, 'OBRA-TESTE-A', { category: 'Material', value: 1, date: '2031-01-16', operationId: 'INVALIDO-TESTE' }, ctx), /data real/);
assert.throws(() => C.saveExtra(state, 'OBRA-TESTE-A', { category: 'Material', value: 1, date: ctx.today, proof: { data: 'javascript:alert(1)' }, operationId: 'INVALIDO-TESTE' }, ctx), /comprovante/);
assert.throws(() => C.saveContract(state, 'OBRA-TESTE-A', { ...input, id: saved.contractId, mode: 'fixed', total: 12, operationId: 'REDUCAO-TESTE' }, ctx), /menor/);
assert.throws(() => C.saveContract(state, 'OBRA-TESTE-A', { ...input, operationId: 'READONLY-TESTE' }, { ...ctx, readOnly: true }), /acesso/);
assert.throws(() => C.saveContract(state, 'OBRA-TESTE-A', { ...input, operationId: 'SEMFINANCEIRO-TESTE' }, { ...ctx, modules: ['works'] }), /acesso/);
assert.throws(() => C.saveContract(state, 'OBRA-TESTE-A', input, { ...ctx, companyId: 'OUTRA-EMPRESA-TESTE' }), /outra empresa/);
state.attendance = [{ id: 'PRESENCA-TESTE', employeeId: 'PESSOA-TESTE', date: ctx.today, workId: 'OBRA-TESTE-A', status: 'Trabalhou' }];
state = W.schedulePhases(state, 'OBRA-TESTE-A', ctx.today, [{ employeeId: 'PESSOA-TESTE', phaseId: 'FASE-TESTE-A', contractId: saved.contractId }], ctx);
assert.equal(C.attendanceMode(state, state.attendance[0]).paymentMode, 'contract');
assert.equal(state.attendance[0].status, 'Trabalhou');
let removed = W.schedulePhases(state, 'OBRA-TESTE-A', ctx.today, [], ctx);
assert.equal(C.attendanceMode(removed, removed.attendance[0]).paymentMode, 'contract', 'remover escala não reaplica diária sobre empreita');
state = W.schedulePhases(state, 'OBRA-TESTE-B', '2031-01-14', [{ employeeId: 'PESSOA-TESTE', phaseId: 'FASE-TESTE-B', contractId: '' }], ctx);
assert.equal(C.attendanceMode(state, { employeeId: 'PESSOA-TESTE', date: '2031-01-14', workId: 'OBRA-TESTE-B' }).paymentMode, 'daily', 'mesma pessoa diária em outra obra');
const labor = { id: 'DIARIA-TESTE', source: 'attendance', workId: 'OBRA-TESTE-A', phaseId: 'FASE-TESTE-A', date: ctx.today, value: 29, kind: 'labor' };
const ledger = [...state.otherExpenses.map((row) => ({ ...row, source: 'otherExpenses', kind: row.costType === 'contractPayment' ? 'contract' : 'other' })), labor, labor, { id: 'REC-TESTE', source: 'receipts', workId: 'OBRA-TESTE-A', date: ctx.today, value: 100, kind: 'receipt' }, { id: 'PAGO-TESTE', source: 'payments', workId: 'OBRA-TESTE-A', date: ctx.today, value: 29, kind: 'payment' }];
const costs = C.breakdown(state, 'OBRA-TESTE-A', ledger);
assert.equal(costs.totalCost, 455.81);
assert.equal(costs.daily, 29); assert.equal(costs.contractPaid, 391.8); assert.equal(costs.extras, 35.01); assert.equal(costs.commitment, 331.95);
assert.equal(costs.byPhase.find((p) => !p.id).total, 11.31);
assert.equal(C.breakdown(state, 'OBRA-TESTE-B', ledger).totalCost, 0);
assert.deepEqual(C.clientContract(state, 'OBRA-TESTE-A'), { value: 12347, source: 'Valor cadastrado no Financeiro' });
assert.deepEqual(state.receivables, initial.receivables); assert.deepEqual(state.payments, initial.payments); assert.deepEqual(state.workMedia, initial.workMedia);
const changed=C.saveContract(state,'OBRA-TESTE-A',{...input,id:saved.contractId,mode:'fixed',total:900,phaseId:'',operationId:'EDICAO-FICTICIA-UNICA'},ctx).state;
assert.equal(changed.workUpdates.length,state.workUpdates.length+1,'uma edição gera um único evento, mesmo alterando valor e fase');
assert.equal(changed.workUpdates.at(-1).kind,'Valor e fase da empreita alterados');
console.log('PASS: diária/empreita por dia e obra, metragem, fechado, parcelas, extras, centavos, duplicação, fases, autorização, contrato do cliente e preservação.');
