import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
const require = createRequire(new URL('../tmp/owner-qa-runtime/package.json', import.meta.url));
const { PGlite } = require('@electric-sql/pglite');
const db = new PGlite();
const owner='51000000-0000-4000-8000-000000000001',supervisor='51000000-0000-4000-8000-000000000002',company='52000000-0000-4000-8000-000000000001';
try {
  await db.exec(`create schema auth; create role anon; create role authenticated; create table auth.users(id uuid primary key);
  create function auth.uid() returns uuid language sql as $$ select nullif(current_setting('test.uid',true),'')::uuid $$; grant usage on schema auth to authenticated;`);
  for (const file of ['202608250900_core_schema_baseline.sql','20260827_activate_company_invites_safely.sql','202609051600_work_control_revision.sql','202609091200_work_costs_guard.sql']) await db.exec((await fs.readFile(new URL('../supabase/migrations/'+file,import.meta.url),'utf8')).replace('create extension if not exists pgcrypto;',''));
  await db.exec(`insert into auth.users values('${owner}'),('${supervisor}');insert into companies(id,name) values('${company}','EMPRESA FICTÍCIA');insert into company_members(company_id,user_id,role,permission_profile) values('${company}','${owner}','owner','gerente'),('${company}','${supervisor}','collaborator','supervisor');`);
  const initial={db:{works:[{id:'OBRA-TESTE',name:'OBRA FICTÍCIA'}],workPhases:[{id:'FASE-TESTE',workId:'OBRA-TESTE'}],workUpdates:[],distributions:[],otherExpenses:[],receivables:[{id:'CLIENTE-TESTE',workId:'OBRA-TESTE',total:7313}]}};
  await db.query('insert into company_app_state(company_id,data) values($1,$2)',[company,initial]);
  const as=async(user)=>{await db.exec('reset role');await db.query("select set_config('test.uid',$1,false)",[user]);await db.exec('set role authenticated');};
  let revision=1;
  const save=async(payload)=>{const result=(await db.query('select save_company_app_state_checked($1,$2,$3) result',[company,payload,revision])).rows[0].result;revision=result.revision;return result;};
  await as(owner);
  const state=structuredClone(initial);
  state.db.works[0].control={empreitas:[{id:'EMPREITA-TESTE',workId:'OBRA-TESTE',companyId:company,name:'SERVIÇO FICTÍCIO',responsible:'PESSOA FICTÍCIA',mode:'meters',quantity:12.5,unitPrice:13.7,total:171.25,phaseId:'FASE-TESTE'}]};
  await save(state);
  state.db.otherExpenses.push({id:'CUSTO-TESTE',workId:'OBRA-TESTE',companyId:company,contractId:'EMPREITA-TESTE',phaseId:'FASE-TESTE',costType:'contractPayment',value:51.13,date:'2031-01-15',operationId:'OPERACAO-TESTE'});
  await save(state);
  const bad=structuredClone(state);bad.db.otherExpenses[0].value=191;
  await assert.rejects(()=>save(bad),/ultrapassam/);
  const duplicated=structuredClone(state);duplicated.db.otherExpenses.push({...duplicated.db.otherExpenses[0]});
  await assert.rejects(()=>save(duplicated),/duplicado/);
  const cross=structuredClone(state);cross.db.otherExpenses[0].contractId='EMPREITA-INEXISTENTE-TESTE';
  await assert.rejects(()=>save(cross),/não pertence/);
  const phase=structuredClone(state);phase.db.otherExpenses[0].phaseId='FASE-OUTRA-TESTE';
  await assert.rejects(()=>save(phase),/Fase do custo/);
  const proof=structuredClone(state);proof.db.otherExpenses[0].proof={data:'javascript:alert(1)'};
  await assert.rejects(()=>save(proof),/Comprovante/);
  const mismatch=structuredClone(state);mismatch.db.works[0].control.empreitas[0].total=198;
  await assert.rejects(()=>save(mismatch),/metragem/);
  const legacy=structuredClone(state);await assert.rejects(()=>db.query('select save_company_app_state($1,$2)',[company,legacy]),/controle de revisão/);
  await as(supervisor);
  const denied=structuredClone(state);denied.db.works[0].control.empreitas[0].name='ALTERAÇÃO NÃO AUTORIZADA FICTÍCIA';
  await assert.rejects(()=>save(denied),/perfil.*empreitas/);
  await as(owner);
  state.db.otherExpenses.push({id:'EXTRA-TESTE',workId:'OBRA-TESTE',companyId:company,phaseId:'',costType:'extra',category:'CUSTOMIZADO FICTÍCIO',value:9.31,date:'2031-01-15',operationId:'EXTRA-OP-TESTE'});
  await save(state);
  await db.exec('reset role');
  const saved=(await db.query('select data from company_app_state where company_id=$1',[company])).rows[0].data;
  assert.deepEqual(saved.db.receivables,initial.db.receivables);assert.equal(saved.db.otherExpenses.length,2);
  // Os novos controles usam o mesmo JSON e a mesma gravação com revisão.
  // Executado apenas no PostgreSQL em memória, com usuário/empresa FICTÍCIOS.
  const coreRequire = createRequire(import.meta.url), C = coreRequire('../public-assets/work-cost-core-v1.js'), W = coreRequire('../public-assets/work-control-core-v1.js');
  let sequence = 0, payload = structuredClone(saved);
  const ctx = { companyId: company, userId: owner, modules: ['works', 'financial'], now: '2031-01-15T12:00:00Z', today: '2031-01-15', id: () => `BANCO-FICTICIO-${++sequence}` };
  await as(owner);
  payload.db = C.saveClientAddendum(payload.db, 'OBRA-TESTE', { description: 'ADITIVO FICTÍCIO', value: 103.27, date: ctx.today, operationId: 'ADITIVO-BANCO-FICTICIO' }, ctx); await save(payload);
  payload.db = C.saveClientForecast(payload.db, 'OBRA-TESTE', { value: 211, expectedDate: '2031-01-17', operationId: 'PREVISAO-BANCO-FICTICIA' }, ctx); await save(payload);
  const closingId = payload.db.workClosings[0].id;
  payload.db = C.saveClientReceipt(payload.db, 'OBRA-TESTE', { closingId, value: 71.3, date: ctx.today, operationId: 'RECIBO-BANCO-FICTICIO' }, ctx); await save(payload);
  payload.db.workPhases = [{ ...payload.db.workPhases[0], percent: 100, status: 'Concluída', controlVersion: 1, weight: 1 }, { id: 'FASE-PENDENTE-BANCO-FICTICIA', workId: 'OBRA-TESTE', name: 'FASE FICTÍCIA', percent: 0, status: 'Não iniciada', controlVersion: 1, weight: 1 }]; await save(payload);
  payload.db = W.deletePhase(payload.db, 'OBRA-TESTE', 'FASE-TESTE', ctx); await save(payload);
  assert.equal(W.workProgress(payload.db, 'OBRA-TESTE').value, 50); assert.equal(payload.db.otherExpenses[0].phaseId, 'FASE-TESTE', 'custo não é apagado nem reatribuído');
  await db.exec('reset role');
  const reloaded = (await db.query('select data from company_app_state where company_id=$1',[company])).rows[0].data.db;
  assert.equal(C.clientAgreement(reloaded, 'OBRA-TESTE').value, 7416.27); assert.equal(C.clientPosition(reloaded, 'OBRA-TESTE').received, 71.3);
  assert.equal(C.clientForecasts(reloaded, 'OBRA-TESTE').pending, 139.7); assert.equal(W.workProgress(reloaded, 'OBRA-TESTE').value, 50);
  assert.deepEqual(reloaded.otherExpenses, saved.db.otherExpenses);
  console.log('CLIENT_FINANCE_DATABASE_OK: contrato/aditivo/previsão/recibo e exclusão de fase com custo vinculado sobrevivem à gravação/releitura; nenhuma alteração nas migrations.');
  console.log('WORK_COST_DATABASE_OK: SQL executado em PostgreSQL isolado, permissões, revisão, centavos, parcelas, fase, duplicação e preservação de receita. Nenhum banco remoto acessado.');
} finally { await db.close(); }
